services:
  integration.rinf:
    image: integration.rinf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
    depends_on:
      - mongodb
    environment:
      - MongoDB__ConnectionString=mongodb+srv://dev:dev@mongodb:27017
      - MongoDB__DatabaseName=Integration_RINF
