# This is a generated file. Not intended for manual editing.
services:
  integration.rinf:
    build:
      context: "C:\\Users\\dylan\\source\\repos\\POC.Infrastructure\\Integration\\\
        Integration.RINF"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Integration.RINF.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "integration.rinf:dev"
    ports: []
    volumes:
    - "C:\\Users\\dylan\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\dylan\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\dylan\\source\\repos\\POC.Infrastructure\\Integration\\Integration.RINF:/app:rw"
    - "C:\\Users\\dylan\\source\\repos\\POC.Infrastructure:/src:rw"
    working_dir: "/app"
