# This is a generated file. Not intended for manual editing.
services:
  integration.rinf:
    build:
      context: "C:\\Users\\dylan\\source\\repos\\POC.Infrastructure\\Integration\\\
        Integration.RINF"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "integration.rinf:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "C:\\Users\\dylan\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\dylan\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\dylan\\source\\repos\\POC.Infrastructure\\Integration\\Integration.RINF:/app:rw"
    - "C:\\Users\\dylan\\source\\repos\\POC.Infrastructure:/src:rw"
    - "C:\\Users\\dylan\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\dylan\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_12_05_00_44_23:/var/opt/rider-debugger:rw"
    working_dir: "/app"
